src/Entity/Victima.php
<?php

namespace App\Entity;

use App\Repository\VictimaRepository;
use Doctrine\ORM\Mapping as ORM;

/**
 * @ORM\Entity(repositoryClass=VictimaRepository::class)
 */
class Victima
{
    /**
     * @ORM\Id
     * @ORM\GeneratedValue
     * @ORM\Column(type="integer")
     */
    private $id;

    /**
     * @ORM\Column(type="string", length=255)
     */
    private $nombre;

    /**
     * @ORM\Column(type="string", length=255)
     */
    private $apellido;

     /**
     * @ORM\ManyToOne(targetEntity=TipoDocumento::class, inversedBy="victimas")
     */
    private $tipoDocumento;

    /**
     * @ORM\Column(type="string", length=255)
     */
    private $nro_documento;

    /**
     * @ORM\ManyToOne(targetEntity=Sexo::class, inversedBy="victimas")
     */
    private $sexo;

    /**
     * @ORM\ManyToOne(targetEntity=Ocupacion::class, inversedBy="victimas")
     */
    private $ocupacion;

    /**
     * @ORM\ManyToOne(targetEntity=Genero::class, inversedBy="victimas")
     */
    private $genero;

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getNombre(): ?string
    {
        return $this->nombre;
    }

    public function setNombre(string $nombre): self
    {
        $this->nombre = $nombre;

        return $this;
    }

    public function getApellido(): ?string
    {
        return $this->apellido;
    }

    public function setApellido(string $apellido): self
    {
        $this->apellido = $apellido;

        return $this;
    }

    public function getTipoDocumento(): ?TipoDocumento
    {
        return $this->tipoDocumento;
    }

    public function setTipoDocumento(?TipoDocumento $tipoDocumento): self
    {
        $this->tipoDocumento = $tipoDocumento;

        return $this;
    }

    public function getNroDocumento(): ?string
    {
        return $this->nro_documento;
    }

    public function setNroDocumento(string $nro_documento): self
    {
        $this->nro_documento = $nro_documento;

        return $this;
    }

    public function getSexo(): ?Sexo
    {
        return $this->sexo;
    }

    public function setSexo(?Sexo $sexo): self
    {
        $this->sexo = $sexo;

        return $this;
    }

    public function getOcupacion(): ?Ocupacion
    {
        return $this->ocupacion;
    }

    public function setOcupacion(?Ocupacion $ocupacion): self
    {
        $this->ocupacion = $ocupacion;

        return $this;
    }

    public function getGenero(): ?Genero
    {
        return $this->genero;
    }

    public function setGenero(?Genero $genero): self
    {
        $this->genero = $genero;

        return $this;
    }
}

src/Form/VictimaType.php
<?php

namespace App\Form;

use App\Entity\Victima;
use Symfony\Component\Form\AbstractType;
use Symfony\Component\Form\FormBuilderInterface;
use Symfony\Component\OptionsResolver\OptionsResolver;

class VictimaType extends AbstractType
{
    public function buildForm(FormBuilderInterface $builder, array $options)
    {
        $builder
            ->add('nombre')
            ->add('apellido')
            ->add('tipoDocumento')
            ->add('nro_documento')
            ->add('sexo')
            ->add('ocupacion')
            ->add('genero')
        ;
    }

    public function configureOptions(OptionsResolver $resolver)
    {
        $resolver->setDefaults([
            'data_class' => Victima::class,
        ]);
    }
}

src/Controller/VictimaController.php
<?php

namespace App\Controller;

use App\Entity\Victima;
use App\Form\VictimaType;
use App\Repository\VictimaRepository;
use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;
use Symfony\Component\HttpFoundation\Request;
use Symfony\Component\HttpFoundation\Response;
use Symfony\Component\Routing\Annotation\Route;

/**
 * @Route("/victima")
 */
class VictimaController extends AbstractController
{
    /**
     * @Route("/", name="victima_index", methods={"GET"})
     */
    public function index(VictimaRepository $victimaRepository): Response
    {
        return $this->render('victima/index.html.twig', [
            'victimas' => $victimaRepository->findAll(),
        ]);
    }

    /**
     * @Route("/new", name="victima_new", methods={"GET","POST"})
     */
    public function new(Request $request): Response
    {
        $victima = new Victima();
        $form = $this->createForm(VictimaType::class, $victima);
        $form->handleRequest($request);

        if ($form->isSubmitted() && $form->isValid()) {
            $entityManager = $this->getDoctrine()->getManager();
            $entityManager->persist($victima);
            $entityManager->flush();

            return $this->redirectToRoute('victima_index', [], Response::HTTP_SEE_OTHER);
        }

        return $this->render('victima/new.html.twig', [
            'victima' => $victima,
            'form' => $form->createView(),
        ]);
    }

    /**
     * @Route("/{id}", name="victima_show", methods={"GET"})
     */
    public function show(Victima $victima): Response
    {
        return $this->render('victima/show.html.twig', [
            'victima' => $victima,
        ]);
    }

    /**
     * @Route("/{id}/edit", name="victima_edit", methods={"GET","POST"})
     */
    public function edit(Request $request, Victima $victima): Response
    {
        $form = $this->createForm(VictimaType::class, $victima);
        $form->handleRequest($request);

        if ($form->isSubmitted() && $form->isValid()) {
            $this->getDoctrine()->getManager()->flush();

            return $this->redirectToRoute('victima_index', [], Response::HTTP_SEE_OTHER);
        }

        return $this->render('victima/edit.html.twig', [
            'victima' => $victima,
            'form' => $form->createView(),
        ]);
    }

    /**
     * @Route("/{id}", name="victima_delete", methods={"POST"})
     */
    public function delete(Request $request, Victima $victima): Response
    {
        if ($this->isCsrfTokenValid('delete'.$victima->getId(), $request->request->get('_token'))) {
            $entityManager = $this->getDoctrine()->getManager();
            $entityManager->remove($victima);
            $entityManager->flush();
        }

        return $this->redirectToRoute('victima_index', [], Response::HTTP_SEE_OTHER);
    }
}

templates/victima/_delete_form.html.twig
<form method="post" action="{{ path('victima_delete', {'id': victima.id}) }}" onsubmit="return confirm('Are you sure you want to delete this item?');">
    <input type="hidden" name="_token" value="{{ csrf_token('delete' ~ victima.id) }}">
    <button class="btn">Delete</button>
</form>

templates/victima/_form.html.twig
<div class="container" style="margin-top:30px">
        {{ form_start(form) }}
            {{ form_widget(form) }}
            <button class="btn btn-success">{{ button_label|default('Guardar') }}</button>
            
            <button class="btn btn-info"> <a href="{{ path('victima_index') }}">Volver a la lista</a></button>
               <br>
               
        {{ form_end(form) }}
   <br>
 
</div>
  <br>

templates/victima/edit.html.twig
{% extends 'base.html.twig' %}

{% block title %}Editar registro{% endblock %}

{% block body %}{{ parent() }}
    <h2>Editar registro</h2>

    {{ include('victima/_form.html.twig', {'button_label': 'Actualizar'}) }}

    <a href="{{ path('victima_index') }}">Volver a la lista</a>

    {##}{{ include('victima/_delete_form.html.twig') }}
{% endblock %}

templates/victima/index.html.twig
{% extends 'base.html.twig' %}

{% block title %}{{ parent() }}-Victima{% endblock %}

{% block body %}{{ parent() }}
<div class="container">
   <h2>Registro de victimas</h2>
  <p>Registro de victimas:</p>    
   <br>   
  <div class="table-responsive-sm">
    <table class="table">
        <thead class="thead-light">
                <tr>
                    <th>Id</th>
                    <th>Nombre</th>
                    <th>Apellido</th>
                    <th>TipoDocumento</th>
                    <th>Numero</th>
                    <th>Generosss</th>
                    <th>Ocupación</th>
                    <th>actions</th>
                </tr>
            </thead>
            <tbody>
            {% for victima in victimas %}
                <tr>
                    <td>{{ victima.id }}</td>
                    <td>{{ victima.nombre }}</td>
                    <td>{{ victima.apellido }}</td>
                    <td>{{ victima.tipoDocumento }}</td>
                    <td>{{ victima.nroDocumento }}</td>
                    <td>{{ victima.genero }}</td>
                     <td>{{ victima.ocupacion }}</td>
                    <td>
                        <a href="{{ path('victima_show', {'id': victima.id}) }}" class="btn btn-info btn-sm" alt="Ver">
                        <span class="glyphicon glyphicon-eye-open"></span> Ver</a>
                          
                        <a href="{{ path('victima_edit', {'id': victima.id}) }}" class="btn btn-warning btn-sm"
                         alt="Editar"><span class="glyphicon glyphicon-pencil"></span> Modificar</a>
                    </td>
                </tr>
            {% else %}
                <tr>
                    <td colspan="6">No se encontraron registros</td>
                </tr>
            {% endfor %}
            </tbody>
        </table>

        <a href="{{ path('victima_new') }}"class="btn btn-primary btn-sm" alt="Nuevo">
                        <span class="glyphicon glyphicon-plus"></span> Nuevo</a>
  </div>
</div>
{% endblock %}

templates/victima/new.html.twig
{% extends 'base.html.twig' %}

{% block title %}{{ parent() }}Alta victima{% endblock %}

{% block body %}{{ parent() }}
    <h2>Dar de alta nueva victima</h2>

    {{ include('victima/_form.html.twig') }}

    <a href="{{ path('victima_index') }}" class="btn btn-default btn-sm">
          <span class="glyphicon glyphicon-step-backward"></span>Volver</a>
{% endblock %}

templates/victima/show.html.twig
{% extends 'base.html.twig' %}

{% block title %}Victima{% endblock %}

{% block body %}{{ parent() }}
    <h3 class="victima">Datos de la victima</h3>
    <br>
<div class="container">
    <table class="table">
        <tbody>
            <tr>
                <th>Id</th>
                <td>{{ victima.id }}</td>
            </tr>
            <tr>
                <th>Nombre</th>
                <td>{{ victima.nombre }}</td>
            </tr>
            <tr>
                <th>Apellido</th>
                <td>{{ victima.apellido }}</td>
            </tr>
            <tr>
                <th>TipoDocumento</th>
                <td>{{ victima.tipoDocumento }}</td>
            </tr>
            <tr>
                <th>Nro_documento</th>
                <td>{{ victima.nroDocumento }}</td>
            </tr>
        </tbody>
    </table>

    <a href="{{ path('victima_index') }}" class="btn btn-info btn-sm"><span class="glyphicon glyphicon-step-backward"></span>Volver</a>

    <a href="{{ path('victima_edit', {'id': victima.id}) }}" class="btn btn-warning btn-sm"
                         alt="Editar"><span class="glyphicon glyphicon-pencil"></span> Modificar</a>
</div>
   {# {{ include('victima/_delete_form.html.twig') }}#}
{% endblock %}